version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/alpine/web/Dockerfile
      args:
        DOCKER_USER_ID: ${DOCKER_USER_ID}
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        ENVIRONMENT: ${ENVIRONMENT}
    image: app-web-${ENVIRONMENT}
    volumes:
      - ./:/opt/app
    ports:
      - '8080:80'
  php:
    build:
      context: .
      dockerfile: docker/alpine/php/Dockerfile
      args:
        DOCKER_USER_ID: ${DOCKER_USER_ID}
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        ENVIRONMENT: ${ENVIRONMENT}
    image: app-php-${ENVIRONMENT}
    volumes:
      - ./:/opt/app
  database:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_ROOT_HOST: ${DATABASE_HOST}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
  migrate:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_ROOT_HOST: ${DATABASE_HOST}
      MYSQL_DATABASE: migrate_${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
