version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/alpine/php/Dockerfile
      args:
        DOCKER_USER_ID: ${DOCKER_USER_ID}
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        ENVIRONMENT: ${ENVIRONMENT}
        DRUPAL_TESTING_COMPOSER_PROJECT: thunder/thunder-project
        DRUPAL_TESTING_DATABASE_USER: ${DATABASE_USER}
        DRUPAL_TESTING_DATABASE_HOST: ${DATABASE_HOST}
        DRUPAL_TESTING_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DRUPAL_TESTING_DATABASE_NAME: ${DATABASE_NAME}
        DRUPAL_TESTING_DRUPAL_VERSION: ~9
        DRUPAL_TESTING_SELENIUM_HOST: selenium
        DRUPAL_TESTING_TEST_DUMP_FILE: db-dump.php
        DRUPAL_TESTING_DATABASE_ENGINE: mysql
        DRUPAL_TESTING_TEST_CODING_STYLES: 0
        DRUPAL_TESTING_TEST_PROFILE: thunder
        DRUPAL_TESTING_TEST_GROUP: Thunder
        DRUPAL_TESTING_HTTP_PORT: 80
        DRUPAL_TESTING_TEST_FILTER: ''
        THUNDER_ADMIN_BRANCH: 4.x
        PHPSTAN_MEMORY_LIMIT: 4G
        DRUPAL_TESTING_PARALLEL_TESTING: 0
        SIMPLETEST_BASE_URL: http://web:80
    image: app-web-${ENVIRONMENT}
    ports:
      - '8080:80'
    volumes:
      - ./:/opt/project
  database:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_ROOT_HOST: ${DATABASE_HOST}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 7900:7900
      - 5901:5900
      - 4444:4444
    volumes:
      - ./docroot/profiles/contrib/thunder/tests/fixtures:/fixtures
    shm_size: '2gb'
volumes:
  test-fixtures:
