#!/bin/sh
#ddev-generated

## Description: Dump the database as PHP file into the docroot.
## Usage: dump-test-database
## Example: ddev dump-test-database

cd "${DDEV_COMPOSER_ROOT}"/"${DDEV_DOCROOT}" || exit

# shellcheck disable=SC2154
php core/scripts/db-tools.php dump-database-d8-mysql > "${thunderDumpFile}"
