name: Run thunder-develop tests

on:
  pull_request:
    branches:
      - 3.x

  schedule:
    - cron:  '0 7 * * *'

jobs:

  test:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '7.4'
          extensions: Imagick

      - name: Start MySql service
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Configure repositories
        run: |
          composer config repositories.thunder git https://github.com/thunder/thunder-distribution.git
          composer config repositories.admin git https://github.com/BurdaMagazinOrg/theme-thunder-admin.git
          composer config repositories.paragraphs_features git https://github.com/thunder/paragraphs_features.git
          composer config repositories.paragraphs_paste git https://github.com/thunder/paragraphs_paste.git
          composer config repositories.select2 git https://github.com/thunder/select2.git
          composer config repositories.ivw git https://github.com/BurdaMagazinOrg/module-ivw_integration.git
          composer config repositories.update_helper git https://github.com/BurdaMagazinOrg/module-update_helper.git
          composer config repositories.sampler git https://github.com/thunder/sampler.git
          composer config repositories.thunder_performance_measurement git https://github.com/thunder/thunder_performance_measurement.git
          composer config repositories.testsite_builder git https://github.com/thunder/testsite_builder.git
          composer config repositories.thunder_testing_demo git https://github.com/thunder/thunder_testing_demo.git

      - name: Install dependencies
        run: |
          composer install

      - name: Install Thunder
        run: |
          cd docroot
          /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush si thunder --db-url=mysql://root:root@127.0.0.1/thunder -y -vvv
